services:
  app:
    image: sergandri/tg_finance_bot-app:latest
    ports:
      - "8200:8200"
    volumes:
      - ./app_data:/app_data
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/app_data/database.sqlite
