# .github/workflows/deploy.yml

name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: sergandri/tg_finance_bot-app:latest

    - name: SSH Deploy to Yandex VM
      uses: appleboy/ssh-action@v0.1.16
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull sergandri/tg_finance_bot-app:latest
          docker stop tg_finance_bot-app || true
          docker rm tg_finance_bot-app || true
          docker run -d -p 8200:8200 --name tg_finance_bot-app -v /app_data:/app_data sergandri/tg_finance_bot-app:latest

