name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tg_finance_bot-app:latest

    - name: SSH Deploy to Yandex VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e  
          sudo docker stop tg_finance_bot-app || true
          sudo docker rm tg_finance_bot-app || true
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tg_finance_bot-app:latest
          sudo nohup docker run -d \
            -p 8200:8200 \ 
            --name tg_finance_bot-app \
            -e API_TOKEN=${{ secrets.API_TOKEN }} \
            -e CURRENCY_API=${{ secrets.CURRENCY_API }} \
            -e DATABASE_PATH=${{ secrets.DATABASE_PATH }} \
            -v /app_data:/app_data \
            ${{ secrets.DOCKERHUB_USERNAME }}/tg_finance_bot-app:latest
